In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [7]:
type(a)

numpy.ndarray

In [8]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [9]:
#creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [15]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [13]:
# to know the shape
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [14]:
print(a2.ndim)
print(a3.ndim)

2
3


In [16]:
print(a2.dtype)

int64


In [22]:
# range
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
#2d array
np.random.randint(1,11, size=(2,3))

array([[[ 4,  7,  3],
        [ 7,  1,  1]],

       [[ 4,  5, 10],
        [ 5,  9,  6]],

       [[ 6,  5,  1],
        [10,  3,  1]]], dtype=int32)

In [28]:
#3d array
np.random.randint(1,11, size=(3,2,3))

array([[[ 9,  8,  9],
        [10,  3,  1]],

       [[ 6,  2,  4],
        [ 3,  1,  1]],

       [[ 3,  8,  5],
        [ 7,  1, 10]]], dtype=int32)

In [29]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[ 3 20]
 [ 2  1]]
[[15  9]
 [ 4  7]]


In [30]:
print(x+y)
print(x-y)
print(x*y)


[[18 29]
 [ 6  8]]
[[-12  11]
 [ -2  -6]]
[[ 45 180]
 [  8   7]]


In [35]:
#1st method
print(x @ y) 

[[125 167]
 [ 34  25]]


In [32]:
#2nd method
np.dot(x,y)

array([[125, 167],
       [ 34,  25]], dtype=int32)

In [34]:
x.prod()

np.int64(120)

In [38]:
x.mean()
y.mean()

np.float64(8.75)

In [39]:
print(x)

[[ 3 20]
 [ 2  1]]


In [41]:
b = x.mean(axis=0)  #column wise
print(b)

[ 2.5 10.5]


In [42]:
c = x.mean(axis=1)  #row wise
print(c)

[11.5  1.5]


In [43]:
print(x.sum())
print(x.std())
print(x.var())

26
7.826237921249264
61.25


In [46]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [47]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[22 76 25 67]
 [21 46 61 48]
 [27 38 15 79]
 [33 57 47 83]]


In [48]:
#convert a matrix size to another matrix size
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[22 76 25 67 21 46 61 48]
 [27 38 15 79 33 57 47 83]]
8x2
[[22 76]
 [25 67]
 [21 46]
 [61 48]
 [27 38]
 [15 79]
 [33 57]
 [47 83]]
