In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
#creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [8]:
# to know the shape
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [9]:
print(a2.ndim)
print(a3.ndim)

2
3


In [10]:
print(a2.dtype)

int64


In [11]:
# range
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
#2d array
np.random.randint(1,11, size=(2,3))

array([[6, 7, 1],
       [5, 2, 1]], dtype=int32)

In [15]:
#3d array
np.random.randint(1,11, size=(3,2,3))

array([[[ 2,  6,  8],
        [ 4,  8,  2]],

       [[ 2, 10,  9],
        [ 6,  1,  3]],

       [[ 1, 10,  9],
        [ 6,  5,  9]]], dtype=int32)

In [16]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[13  7]
 [ 3 11]]
[[18 20]
 [ 7  6]]


In [17]:
print(x+y)
print(x-y)
print(x*y)


[[31 27]
 [10 17]]
[[ -5 -13]
 [ -4   5]]
[[234 140]
 [ 21  66]]


In [18]:
#1st method
print(x @ y) 

[[283 302]
 [131 126]]


In [19]:
#2nd method
np.dot(x,y)

array([[283, 302],
       [131, 126]], dtype=int32)

In [20]:
x.prod()

np.int64(3003)

In [21]:
x.mean()
y.mean()

np.float64(12.75)

In [22]:
print(x)

[[13  7]
 [ 3 11]]


In [23]:
b = x.mean(axis=0)  #column wise
print(b)

[8. 9.]


In [24]:
c = x.mean(axis=1)  #row wise
print(c)

[10.  7.]


In [25]:
print(x.sum())
print(x.std())
print(x.var())

34
3.840572873934304
14.75


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [27]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[58 97 49 67]
 [48 89 70 64]
 [96 57 50 66]
 [45 12 56 70]]


In [28]:
#convert a matrix size to another matrix size
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[58 97 49 67 48 89 70 64]
 [96 57 50 66 45 12 56 70]]
8x2
[[58 97]
 [49 67]
 [48 89]
 [70 64]
 [96 57]
 [50 66]
 [45 12]
 [56 70]]


In [29]:
print(arr2)

[[58 97 49 67]
 [48 89 70 64]
 [96 57 50 66]
 [45 12 56 70]]


In [35]:
print(arr2[0])      #0th row
print(arr2[0,1])        #0th roe 1st column
print(arr2[-1])        #last row
print(arr2[:3])        
print(arr2[3:])        
print(arr2[1:])        

[58 97 49 67]
97
[45 12 56 70]
[[58 97 49 67]
 [48 89 70 64]
 [96 57 50 66]]
[[45 12 56 70]]
[[48 89 70 64]
 [96 57 50 66]
 [45 12 56 70]]


In [43]:
arr2 > 60

array([[False,  True, False,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [44]:
y = arr2[arr2>60]
z = y.reshape(4,2)
print(z)

[[97 67]
 [89 70]
 [64 96]
 [66 70]]
